// app/components/flypy/FlypyPinyinAlphabet.vue
<script setup lang="ts">
import { ref } from 'vue'
import { FLYPY_PINYIN_ALPHABET } from './flypy-alphabet-data'
import type { PinyinAlphabetItem, PinyinAlphabetSection } from './flypy-alphabet-data'

const hoveredGroup = ref<string | null>(null)

function sectionActive(section: PinyinAlphabetSection): boolean {
  return hoveredGroup.value?.startsWith(`${section.tone}:`) ?? false
}

function groupClass(item: PinyinAlphabetItem): string {
  return item.groupColor ? `flypy-group-${item.groupColor}` : ''
}

function cardClass(section: PinyinAlphabetSection, item: PinyinAlphabetItem): Record<string, boolean> {
  const active = Boolean(item.groupKey) && hoveredGroup.value === item.groupKey
  const dimmed = Boolean(item.groupKey) && sectionActive(section) && hoveredGroup.value !== item.groupKey
  return { active, dimmed }
}

function onCardEnter(item: PinyinAlphabetItem) {
  if (item.groupKey)
    hoveredGroup.value = item.groupKey
}
</script>

<template>
  <div class="flypy-alphabet-outer">
    <div class="flypy-alphabet-wrap">
      <section
        v-for="section in FLYPY_PINYIN_ALPHABET"
        :key="section.title"
        :class="['flypy-alphabet-section', section.tone]"
      >
        <h3 :class="['flypy-alphabet-section-title', section.tone]">
          {{ section.title }}
        </h3>
        <div class="flypy-alphabet-grid" @mouseleave="hoveredGroup = null">
          <article
            v-for="item in section.items"
            :key="`${section.tone}-${item.pinyin}`"
            :class="['flypy-key-size', 'flypy-alphabet-card', cardClass(section, item)]"
            @mouseenter="onCardEnter(item)"
          >
            <div v-if="item.category" class="flypy-alphabet-card-head">
              <span
                :class="['flypy-alphabet-card-category', groupClass(item)]"
              >
                {{ item.category }}
              </span>
            </div>
            <div class="flypy-alphabet-card-body">
              <div class="flypy-alphabet-card-pinyin-wrap">
                <span
                  :class="['flypy-alphabet-card-pinyin', section.tone, groupClass(item)]"
                >
                  {{ item.pinyin }}
                </span>
              </div>
              <div class="flypy-alphabet-card-footer">
                <span class="flypy-alphabet-card-hanzi">{{ item.hanzi }}</span>
              </div>
            </div>
          </article>
        </div>
      </section>
    </div>
  </div>
</template>

// src/components/flypy/FlypyPinyinAlphabet.tsx
import { useState } from 'react'
import { cn } from '@/lib/utils'
import {
  flypyAlphabetCardBodyClass,
  flypyAlphabetCardCategoryClass,
  flypyAlphabetCardClass,
  flypyAlphabetCardFooterClass,
  flypyAlphabetCardHanziClass,
  flypyAlphabetCardHeadClass,
  flypyAlphabetCardPinyinClass,
  flypyAlphabetCardPinyinWrapClass,
  flypyAlphabetGridClass,
  flypyAlphabetSectionClass,
  flypyAlphabetSectionTitleClass,
  flypyAlphabetWrapClass,
  flypyBoardStyle,
} from './flypy-classes'
import type { PinyinAlphabetItem, PinyinAlphabetSection } from './flypy-alphabet-data'
import { FLYPY_PINYIN_ALPHABET } from './flypy-alphabet-data'

type FlypyAlphabetCardProps = {
  section: PinyinAlphabetSection
  item: PinyinAlphabetItem
  isActive: boolean
  isDimmed: boolean
  onHoverGroup: (groupKey: string) => void
}

function FlypyAlphabetCard({
  section,
  item,
  isActive,
  isDimmed,
  onHoverGroup,
}: FlypyAlphabetCardProps) {
  return (
    <article
      className={flypyAlphabetCardClass({
        active: isActive,
        dimmed: isDimmed,
      })}
      onMouseEnter={() => {
        if (item.groupKey) onHoverGroup(item.groupKey)
      }}
      title={item.category ? `${item.category} · ${item.hanzi}` : item.hanzi}
    >
      {item.category ? (
        <div className={flypyAlphabetCardHeadClass}>
          <span className={cn(flypyAlphabetCardCategoryClass, item.groupColor)}>
            {item.category}
          </span>
        </div>
      ) : null}
      <div className={flypyAlphabetCardBodyClass}>
        <div className={flypyAlphabetCardPinyinWrapClass}>
          <span className={flypyAlphabetCardPinyinClass(section.tone, item.groupColor)}>
            {item.pinyin}
          </span>
        </div>
        <div className={flypyAlphabetCardFooterClass}>
          <span className={flypyAlphabetCardHanziClass}>{item.hanzi}</span>
        </div>
      </div>
    </article>
  )
}

export function FlypyPinyinAlphabet() {
  const [hoveredGroup, setHoveredGroup] = useState<string | null>(null)

  return (
    <div className={flypyAlphabetWrapClass}>
      {FLYPY_PINYIN_ALPHABET.map(section => {
        const sectionActive = hoveredGroup?.startsWith(`${section.tone}:`) ?? false

        return (
          <section className={flypyAlphabetSectionClass(section.tone)} key={section.title}>
            <h3 className={flypyAlphabetSectionTitleClass(section.tone)}>{section.title}</h3>
            <div
              className={flypyAlphabetGridClass}
              onMouseLeave={() => setHoveredGroup(null)}
              style={flypyBoardStyle}
            >
              {section.items.map(item => (
                <FlypyAlphabetCard
                  isActive={!!item.groupKey && hoveredGroup === item.groupKey}
                  isDimmed={
                    !!item.groupKey && sectionActive && hoveredGroup !== item.groupKey
                  }
                  item={item}
                  key={`${section.tone}-${item.pinyin}`}
                  onHoverGroup={setHoveredGroup}
                  section={section}
                />
              ))}
            </div>
          </section>
        )
      })}
    </div>
  )
}

export default FlypyPinyinAlphabet
